# fly.toml app configuration file generated for pokedex-list on 2023-12-11T15:42:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokedex-list"
primary_region = "jnb"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_OPTIONS = "--openssl-legacy-provider"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
