name: Site Health Check

on:
  schedule:
    - cron: '0 17 * * 2'
    - cron: '0 10 * * 3'
  push:
    branches:
      - master

jobs:
  site_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 
      - name: Check site health on push to master
        if: ${{github.event_name == 'push'}}
        uses: jtalk/url-health-check-action@v3.2
        with:
          url:  https://pokedex-list.fly.dev/
      - name: Check deployed service URL on Tuesday 17:00 UTC
        if: github.event.schedule == '0 17 * * 2'
        uses: jtalk/url-health-check-action@v3.2
        with:
          url:  https://pokedex-list.fly.dev/
      - name: Check site health on Wednesday 10:00 UTC
        if: github.event.schedule == '0 10 * * 3'
        uses: jtalk/url-health-check-action@v3.2
        with:
          url:  https://pokedex-list.fly.dev/
  webhook_notify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Successful Live Site
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{success()}}
        with:
          severity: info
          text: Site up and running. No issues 
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
      - name: Failed Live Site
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{failure()}}
        with:
          severity: error
          text: Site down. Not loading
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
