name: Hello World!

on:
  push:
    branches:
      - master


jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
    - name: Say Hello
      run: |
        echo "Hello World!"
    - name: Todays Date
      run: |
        date
    - name: Current Directory
      run: |
        ls
